#!/usr/bin/env node
/**
 * refresh-events.mjs
 * Pulls time-sensitive events into data/events.json.
 *
 * Strategy (robust + dependency-free, runs on Node 20+ in GitHub Actions):
 *   1. For each source, fetch the page HTML.
 *   2. Extract schema.org JSON-LD "Event" objects (widely used by event calendars).
 *   3. Normalize to our event shape and keep only current/upcoming events.
 *   4. If a source yields nothing (site changed, temporarily down), we DON'T wipe
 *      the calendar — we keep the previous events for that source. The site never
 *      ends up with an empty planner because one scrape failed.
 *
 * To add richer per-site parsing later, extend parseSource() with a site-specific
 * branch. The JSON-LD path already covers any source that publishes Event markup.
 */
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "..", "data", "events.json");

const SOURCES = [
  { id: "medora",      name: "Medora.com",                 url: "https://www.medora.com/events/" },
  { id: "cowboy-hall", name: "ND Cowboy Hall of Fame",     url: "https://northdakotacowboy.org/events/" },
  { id: "trnp",        name: "TR National Park Events (NPS)", url: "https://www.nps.gov/thro/planyourvisit/calendar.htm" },
  { id: "chamber",     name: "Medora Chamber of Commerce", url: "https://medorachamber.com/events/" }
];

const UA = "Mozilla/5.0 (compatible; TRLibraryTripPlanner/1.0; +https://trip.labs.trlibrary.com)";
const HORIZON_DAYS = 400; // keep events up to ~13 months out

function slug(s) { return String(s).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60); }

function collectJsonLd(html) {
  const out = [];
  const re = /<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;
  let m;
  while ((m = re.exec(html))) {
    try {
      const data = JSON.parse(m[1].trim());
      const arr = Array.isArray(data) ? data : (data["@graph"] ? data["@graph"] : [data]);
      for (const node of arr) {
        const t = node && node["@type"];
        const isEvent = t === "Event" || (Array.isArray(t) && t.includes("Event")) || (typeof t === "string" && /Event$/.test(t));
        if (isEvent) out.push(node);
      }
    } catch { /* ignore malformed blocks */ }
  }
  return out;
}

function normalize(node, source) {
  const title = (node.name || "").trim();
  if (!title) return null;
  const start = (node.startDate || "").slice(0, 10) || null;
  const end = (node.endDate || node.startDate || "").slice(0, 10) || null;
  let loc = "";
  if (typeof node.location === "string") loc = node.location;
  else if (node.location && node.location.name) loc = node.location.name;
  let url = node.url || "";
  if (url && url.startsWith("/")) url = new URL(url, source.url).href;
  return {
    id: source.id + "-" + slug(title) + (start ? "-" + start : ""),
    title, source: source.id, start, end,
    allDay: true,
    location: loc || "",
    url: url || source.url,
    tags: []
  };
}

async function parseSource(source) {
  const res = await fetch(source.url, { headers: { "User-Agent": UA }, redirect: "follow" });
  if (!res.ok) throw new Error("HTTP " + res.status);
  const html = await res.text();
  const nodes = collectJsonLd(html);
  const events = nodes.map((n) => normalize(n, source)).filter(Boolean);
  // de-dup by id
  const seen = new Set();
  return events.filter((e) => (seen.has(e.id) ? false : (seen.add(e.id), true)));
}

function upcoming(events) {
  const today = new Date().toISOString().slice(0, 10);
  const horizon = new Date(Date.now() + HORIZON_DAYS * 864e5).toISOString().slice(0, 10);
  return events.filter((e) => {
    const ref = e.end || e.start;
    if (!ref) return true;              // keep undated recurring items
    return ref >= today && (e.start || ref) <= horizon;
  });
}

async function main() {
  let prev = { events: [] };
  try { prev = JSON.parse(await readFile(OUT, "utf8")); } catch { /* first run */ }

  const collected = [];
  for (const source of SOURCES) {
    try {
      const evs = await parseSource(source);
      if (evs.length) {
        console.log(`✓ ${source.name}: ${evs.length} events`);
        collected.push(...evs);
      } else {
        console.log(`• ${source.name}: no JSON-LD events found — keeping previous`);
        collected.push(...(prev.events || []).filter((e) => e.source === source.id));
      }
    } catch (err) {
      console.log(`✗ ${source.name}: ${err.message} — keeping previous`);
      collected.push(...(prev.events || []).filter((e) => e.source === source.id));
    }
  }

  const events = upcoming(collected).sort((a, b) => (a.start || "").localeCompare(b.start || ""));

  const out = {
    note: "AUTO-GENERATED by scripts/refresh-events.mjs via GitHub Actions. Do not hand-edit; edits are overwritten on the next refresh.",
    generatedAt: new Date().toISOString(),
    sources: SOURCES,
    events: events.length ? events : (prev.events || [])
  };

  await writeFile(OUT, JSON.stringify(out, null, 2) + "\n");
  console.log(`\nWrote ${out.events.length} events to data/events.json`);
}

main().catch((e) => { console.error(e); process.exit(1); });
